DATASET:
  CACHE: ./cache/IEMOCAP_sp_31/
  EMOTIONS:
  - angry
  - neutral
  - happy
  - sad
  PATH:
    CREMA-D: ./data/CREMA-D
    EmoDB: ./data/EmoDB
    EmoV-DB: ./data/EmoV-DB
    IEMOCAP: ./data/IEMOCAP
    RAVDESS: ./data/RAVDESS
  TEST_SPLIT: 0.01
  TRAINING_DATASET: ./data/combined/
  VAL_SPLIT: 0.05
INPUT:
  FRAME_PERIOD: 5.0
  NUM_MCEP: 31
  SP_DIM: 512
  N_FRAMES: 384
  SAMPLING_RATE: 16000
SOLVER:
  BATCH_SIZE: 4
  BETA_MAX: 0.02
  BETA_MIN: 0.0001
  CHANNELS: 1
  CHECKPOINT_DIR: ./model_checkpoint/
  CLASS_EMB_DIM: 64
  LR: 5.0e-06
  MAX_EPOCHS: 15
  OPTIMIZER: adam
  RUN_NAME: diffusion_run 
  TIMESTEPS: 5000
